version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8086:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:

volumes:
  jenkins_home:
    external: true
